services:
  xuecodex-rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xuecodex-rag
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./site/docs:/app/site/docs
      - ./rag_api:/app/rag_api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xuerag.rule=Host(`api.xuecodex.tech`)"
      - "traefik.http.routers.xuerag.entrypoints=websecure"
      - "traefik.http.routers.xuerag.tls.certresolver=letsencrypt"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
