services:
  xuecodex-rag:
    image: python:3.10-slim
    container_name: xuecodex-rag
    restart: always
    volumes:
      - ./docs:/app/site/docs # Mount your markdown docs
      - ./rag_api.py:/app/rag_api.py # Make sure this is a file mount
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && uvicorn rag_api:app --host 0.0.0.0 --port 8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xuerag.rule=Host(`api.xuecodex.tech`)"
      - "traefik.http.routers.xuerag.entrypoints=websecure"
      - "traefik.http.routers.xuerag.tls.certresolver=letsencrypt"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
